name: Deploy to cPanel

on:
  push:
    branches: [main] # Change to your preferred branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Archive production build
        run: tar -czf production.tar.gz .next package.json package-lock.json public

      - name: Deploy to cPanel via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }} # Your cPanel server or IP address
          username: ${{ secrets.CPANEL_USERNAME }} # Your cPanel username
          password: ${{ secrets.CPANEL_PASSWORD }} # Your cPanel password
          port: 22
          source: "production.tar.gz"
          target: "/frontend.homefindereg.com" # For example: /home/username/public_html/frontend

      - name: Restart Node.js Application on cPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 22
          script: |
            cd /frontend.homefindereg.com
            tar -xzf production.tar.gz
            npm install --production
